# Generated by Django 5.1.4 on 2024-12-16 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_contactusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
