"""
Django settings for capital_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from decouple import config

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0)zskuk2-mngawe+=)2lhd76aszurnxn55-^i85vj3(khbfsgo'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_BACKEND =  config('EMAIL_BACKEND')
CONTACT_RECIPIENT_EMAIL = config('CONTACT_RECIPIENT_EMAIL')
LOAN_RECEPIENT_EMAIL = config('LOAN_RECEPIENT_EMAIL')

#ALLOWED_HOSTS = ['254capitalemailserver-production.up.railway.app','51.20.79.89','51.20.79.89:8000','13.48.141.185', 'api.254-capital.com',"*"]


#CORS_ALLOWED_ORIGINS = ["https://254capital-production.up.railway.app","http://51.20.79.89:3000","https://254-capital.com", "http://13.48.141.185:3000","https://api.254-capital.com/","*"]
#CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "https://254-capital.com",
#     "https://www.254-capital.com",
#     "http://254-capital.com",
#     "http://www.254-capital.com",
#     "https://254-capital.vercel.app",
#     "https://216.198.79.1/",
#     "https://66.33.60.35/"
# ]
CORS_ALLOWED_ORIGINS = [
    "https://254-capital.vercel.app",  # Vercel frontend
    "https://254-capital.com",        # Production domain
    "http://localhost:3000",
    "https://www.254-capital.vercel.app",
    "https://www.254-capital.com",# Local development
    "https://254capitalemailserver-production.up.railway.app"
]

CORS_ALLOW_ALL_ORIGINS = True  # Temporary for debugging
#CORS_ALLOW_CREDENTIALS = True


# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://\w+\.254-capital\.com$",
# ]


# Add these settings
# CORS_ALLOW_CREDENTIALS = True
# CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
# CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
   
]
CSRF_TRUSTED_ORIGINS = [

    "http://localhost:3000",
    "http://172.0.0.1:3000",

]

# Optional: Remove wildcard configuration if possible
ALLOWED_HOSTS = [
    '254capitalemailserver-production.up.railway.app',
    '51.20.79.89',
    '51.20.79.89:8000',
    '13.48.141.185',
    'api.254-capital.com',
    'www.api.254-capital.com',
    'localhost',
    '127.0.0.1'
]
# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'emails',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'capital_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capital_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'), 
# ]

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
